# Generated by Django 4.1.7 on 2023-03-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membar_img', models.ImageField(upload_to='teams/')),
                ('name', models.CharField(max_length=200, null=True)),
                ('my_self', models.TextField(blank=True, max_length=700, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter', models.URLField(blank=True, max_length=100, unique=True)),
                ('instagram', models.URLField(blank=True, max_length=100, unique=True)),
                ('linkedin', models.URLField(blank=True, max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('professional_sd', models.TextField(blank=True, max_length=700, null=True)),
                ('educational_ed', models.TextField(blank=True, max_length=700, null=True)),
                ('top_1_skills', models.CharField(blank=True, max_length=200, null=True)),
                ('top_1_sp', models.PositiveIntegerField(blank=True, max_length=200, null=True)),
                ('top_2_skills', models.CharField(blank=True, max_length=200, null=True)),
                ('top_2_sp', models.PositiveIntegerField(blank=True, max_length=200, null=True)),
                ('top_3_skills', models.CharField(blank=True, max_length=200, null=True)),
                ('top_3_sp', models.PositiveIntegerField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('time_period', models.CharField(blank=True, max_length=200, null=True)),
                ('designation', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
