# Generated by Django 4.1.7 on 2023-03-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='top_1_sp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='top_2_sp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='top_3_sp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
