# Generated by Django 4.1.7 on 2023-03-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_teams_top_1_sp_alter_teams_top_2_sp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='designation_previous',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='teams',
            name='designation',
            field=models.CharField(max_length=200),
        ),
    ]
