# Generated by Django 4.1.7 on 2023-03-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardBSA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img_bsa', models.ImageField(upload_to='bsa_service/card/')),
                ('title_slogan_bsa', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBenefitBSA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_benefit_img_bsa', models.ImageField(upload_to='bsa_service/customerBenefit/')),
                ('title_bsa', models.CharField(max_length=200)),
                ('description_bsa', models.TextField(max_length=1024)),
                ('customer_service_bsa_1', models.CharField(max_length=200)),
                ('customer_service_bsa_2', models.CharField(max_length=200)),
                ('customer_service_bsa_3', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBSA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_img_bsa', models.ImageField(upload_to='bsa_service/service/')),
                ('title_bsa', models.CharField(max_length=200)),
                ('description_first_para_bsa', models.TextField(max_length=1024)),
                ('description_second_para_bsa', models.TextField(max_length=1024)),
                ('service_details_card_title_bsa_1', models.CharField(max_length=200)),
                ('service_details_card_details_bsa_1', models.CharField(max_length=200)),
                ('service_details_card_title_bsa_2', models.CharField(max_length=200)),
                ('service_details_card_details_bsa_2', models.CharField(max_length=200)),
            ],
        ),
    ]
