# Generated by Django 4.1.7 on 2023-03-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membar_img', models.ImageField(upload_to='news_update/')),
                ('organization', models.CharField(max_length=200, null=True)),
                ('headline', models.CharField(max_length=200)),
                ('descriptions_1', models.TextField(blank=True, max_length=700, null=True)),
                ('descriptions_2', models.TextField(blank=True, max_length=700, null=True)),
                ('descriptions_3', models.TextField(blank=True, max_length=700, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
