# Generated by Django 4.1.7 on 2023-03-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_update', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsupdate',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newsupdate',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
