# Generated by Django 4.1.7 on 2023-03-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img_cm', models.ImageField(upload_to='cm_service/card/')),
                ('title_slogan_cm', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBenefitCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_benefit_img_cm', models.ImageField(upload_to='cm_service/customerBenefit/')),
                ('title_cm', models.CharField(max_length=200)),
                ('description_cm', models.TextField(max_length=1024)),
                ('customer_service_cm_1', models.CharField(max_length=200)),
                ('customer_service_cm_2', models.CharField(max_length=200)),
                ('customer_service_cm_3', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_img_cm', models.ImageField(upload_to='cm_service/service/')),
                ('title_cm', models.CharField(max_length=200)),
                ('description_first_para_cm', models.TextField(max_length=1024)),
                ('description_second_para_cm', models.TextField(max_length=1024)),
                ('service_details_card_title_cm_1', models.CharField(max_length=200)),
                ('service_details_card_details_cm_1', models.CharField(max_length=200)),
                ('service_details_card_title_cm_2', models.CharField(max_length=200)),
                ('service_details_card_details_cm_2', models.CharField(max_length=200)),
            ],
        ),
    ]
