# Generated by Django 4.1.7 on 2023-03-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img_co', models.ImageField(upload_to='co_service/card/')),
                ('title_slogan_co', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBenefitCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_benefit_img_co', models.ImageField(upload_to='co_service/customerBenefit/')),
                ('title_co', models.CharField(max_length=200)),
                ('description_co', models.TextField(max_length=1024)),
                ('customer_service_co_1', models.CharField(max_length=200)),
                ('customer_service_co_2', models.CharField(max_length=200)),
                ('customer_service_co_3', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_img_co', models.ImageField(upload_to='co_service/service/')),
                ('title_co', models.CharField(max_length=200)),
                ('description_first_para_co', models.TextField(max_length=1024)),
                ('description_second_para_co', models.TextField(max_length=1024)),
                ('service_details_card_title_co_1', models.CharField(max_length=200)),
                ('service_details_card_details_co_1', models.CharField(max_length=200)),
                ('service_details_card_title_co_2', models.CharField(max_length=200)),
                ('service_details_card_details_co_2', models.CharField(max_length=200)),
            ],
        ),
    ]
