# Generated by Django 4.1.7 on 2023-03-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img_ca', models.ImageField(upload_to='ca_service/card/')),
                ('title_slogan_ca', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBenefitCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_benefit_img_ca', models.ImageField(upload_to='ca_service/customerBenefit/')),
                ('title_ca', models.CharField(max_length=200)),
                ('description_ca', models.TextField(max_length=1024)),
                ('customer_service_ca_1', models.CharField(max_length=200)),
                ('customer_service_ca_2', models.CharField(max_length=200)),
                ('customer_service_ca_3', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_img_ca', models.ImageField(upload_to='ca_service/service/')),
                ('title_ca', models.CharField(max_length=200)),
                ('description_first_para_ca', models.TextField(max_length=1024)),
                ('description_second_para_ca', models.TextField(max_length=1024)),
                ('service_details_card_title_ca_1', models.CharField(max_length=200)),
                ('service_details_card_details_ca_1', models.CharField(max_length=200)),
                ('service_details_card_title_ca_2', models.CharField(max_length=200)),
                ('service_details_card_details_ca_2', models.CharField(max_length=200)),
            ],
        ),
    ]
