# Generated by Django 4.1.7 on 2023-03-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img_ar', models.ImageField(upload_to='ar_service/card/')),
                ('title_slogan_ar', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBenefitAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_benefit_img_ar', models.ImageField(upload_to='ar_service/customerBenefit/')),
                ('title_ar', models.CharField(max_length=200)),
                ('description_ar', models.TextField(max_length=1024)),
                ('customer_service_ar_1', models.CharField(max_length=200)),
                ('customer_service_ar_2', models.CharField(max_length=200)),
                ('customer_service_ar_3', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_img_ar', models.ImageField(upload_to='ar_service/service/')),
                ('title_ar', models.CharField(max_length=200)),
                ('description_first_para_ar', models.TextField(max_length=1024)),
                ('description_second_para_ar', models.TextField(max_length=1024)),
                ('service_details_card_title_ar_1', models.CharField(max_length=200)),
                ('service_details_card_details_ar_1', models.CharField(max_length=200)),
                ('service_details_card_title_ar_2', models.CharField(max_length=200)),
                ('service_details_card_details_ar_2', models.CharField(max_length=200)),
            ],
        ),
    ]
