# Generated by Django 4.1.7 on 2023-03-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('our_clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourclient',
            old_name='sliders_img',
            new_name='clients_img',
        ),
    ]
