# Generated by Django 4.1.7 on 2023-03-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotlineInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotline_title', models.CharField(max_length=200)),
                ('contact_img', models.ImageField(upload_to='contact/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('telephone_no', models.CharField(blank=True, max_length=200)),
                ('opening_title', models.CharField(blank=True, max_length=200)),
                ('day', models.CharField(blank=True, max_length=200)),
                ('time', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_title', models.CharField(max_length=200)),
                ('sub_office', models.CharField(max_length=200)),
                ('sub_office_location', models.CharField(blank=True, max_length=200)),
                ('head_office', models.CharField(blank=True, max_length=200)),
                ('head_office_location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
