# Generated by Django 4.1.7 on 2023-03-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='businessGoal/img/')),
                ('small_img', models.ImageField(upload_to='businessGoal/on_img/')),
                ('pre_title', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('support_title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=700)),
            ],
        ),
    ]
