# Generated by Django 4.1.7 on 2023-03-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_goal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessgoal',
            old_name='description',
            new_name='description_1',
        ),
        migrations.RenameField(
            model_name='businessgoal',
            old_name='support_title',
            new_name='support_title_1',
        ),
        migrations.AddField(
            model_name='businessgoal',
            name='description_2',
            field=models.TextField(default=' ', max_length=700),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessgoal',
            name='support_title_2',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
