# Generated by Django 4.1.7 on 2023-03-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img_cr', models.ImageField(upload_to='cr_service/card/')),
                ('title_slogan_cr', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBenefitCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_benefit_img_cr', models.ImageField(upload_to='cr_service/customerBenefit/')),
                ('title_cr', models.CharField(max_length=200)),
                ('description_cr', models.TextField(max_length=1024)),
                ('customer_service_cr_1', models.CharField(max_length=200)),
                ('customer_service_cr_2', models.CharField(max_length=200)),
                ('customer_service_cr_3', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_img_cr', models.ImageField(upload_to='cr_service/service/')),
                ('title_cr', models.CharField(max_length=200)),
                ('description_first_para_cr', models.TextField(max_length=1024)),
                ('description_second_para_cr', models.TextField(max_length=1024)),
                ('service_details_card_title_cr_1', models.CharField(max_length=200)),
                ('service_details_card_details_cr_1', models.CharField(max_length=200)),
                ('service_details_card_title_cr_2', models.CharField(max_length=200)),
                ('service_details_card_details_cr_2', models.CharField(max_length=200)),
            ],
        ),
    ]
