# Generated by Django 4.1.7 on 2023-03-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(blank=True, max_length=200, null=True)),
                ('Short_description_1', models.TextField(blank=True, max_length=700, null=True)),
                ('title_2', models.CharField(blank=True, max_length=200, null=True)),
                ('Short_description_2', models.TextField(blank=True, max_length=700, null=True)),
                ('title_3', models.CharField(blank=True, max_length=200, null=True)),
                ('Short_description_3', models.TextField(blank=True, max_length=700, null=True)),
                ('title_4', models.CharField(blank=True, max_length=200, null=True)),
                ('Short_description_4', models.TextField(blank=True, max_length=700, null=True)),
                ('title_5', models.CharField(blank=True, max_length=200, null=True)),
                ('Short_description_5', models.TextField(blank=True, max_length=700, null=True)),
                ('title_6', models.CharField(blank=True, max_length=200, null=True)),
                ('Short_description_6', models.TextField(blank=True, max_length=700, null=True)),
                ('title_7', models.CharField(blank=True, max_length=200, null=True)),
                ('Short_description_7', models.TextField(blank=True, max_length=700, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ARService',
        ),
        migrations.DeleteModel(
            name='AVVService',
        ),
        migrations.DeleteModel(
            name='CASService',
        ),
        migrations.DeleteModel(
            name='CCGCRService',
        ),
        migrations.DeleteModel(
            name='CITCService',
        ),
        migrations.DeleteModel(
            name='CMService',
        ),
        migrations.DeleteModel(
            name='IMAService',
        ),
    ]
