# Generated by Django 4.1.7 on 2023-03-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_delete_arservice_delete_avvservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='pre_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
