# Generated by Django 4.1.7 on 2023-03-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_img', models.ImageField(upload_to='feature/')),
                ('pre_title', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=700)),
                ('feature_1', models.CharField(blank=True, max_length=200)),
                ('feature_2', models.CharField(blank=True, max_length=200)),
                ('feature_3', models.CharField(blank=True, max_length=200)),
                ('feature_4', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
