# Generated by Django 4.1.7 on 2023-03-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_text', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('with_title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=700)),
                ('sliders_img', models.ImageField(upload_to='sliders/')),
            ],
        ),
    ]
