# Generated by Django 4.1.7 on 2023-03-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardAVV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img_avv', models.ImageField(upload_to='avv_service/card/')),
                ('title_slogan_avv', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBenefitAVV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_benefit_img_avv', models.ImageField(upload_to='avv_service/customerBenefit/')),
                ('title_avv', models.CharField(max_length=200)),
                ('description_avv', models.TextField(max_length=1024)),
                ('customer_service_avv_1', models.CharField(max_length=200)),
                ('customer_service_avv_2', models.CharField(max_length=200)),
                ('customer_service_avv_3', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAVV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_img_avv', models.ImageField(upload_to='avv_service/service/')),
                ('title_avv', models.CharField(max_length=200)),
                ('description_first_para_avv', models.TextField(max_length=1024)),
                ('description_second_para_avv', models.TextField(max_length=1024)),
                ('service_details_card_title_avv_1', models.CharField(max_length=200)),
                ('service_details_card_details_avv_1', models.CharField(max_length=200)),
                ('service_details_card_title_avv_2', models.CharField(max_length=200)),
                ('service_details_card_details_avv_2', models.CharField(max_length=200)),
            ],
        ),
    ]
