# Generated by Django 4.1.7 on 2023-03-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='aboutUs/img/')),
                ('small_img', models.ImageField(upload_to='aboutUs/on_img/')),
                ('time_no', models.IntegerField()),
                ('time', models.CharField(choices=[('', 'Select'), ('Days', 'Days'), ('Months', 'Months'), ('Years', 'Years')], max_length=64, null=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_slogan', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=700)),
                ('detail_1', models.CharField(max_length=200)),
                ('detail_2', models.CharField(max_length=200)),
                ('detail_3', models.CharField(max_length=200)),
                ('detail_4', models.CharField(max_length=200)),
                ('detail_5', models.CharField(max_length=200)),
                ('detail_6', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FounderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder_img', models.ImageField(upload_to='aboutUs/founder/')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=200)),
            ],
        ),
    ]
