# Generated by Django 4.1.7 on 2023-03-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('working_time', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100, unique=True)),
                ('facebook', models.URLField(max_length=100, unique=True)),
                ('twitter', models.URLField(max_length=100, unique=True)),
                ('instagram', models.URLField(max_length=100, unique=True)),
                ('linkedin', models.URLField(max_length=100, unique=True)),
                ('logo_img', models.ImageField(upload_to='settings/')),
            ],
        ),
    ]
