# Generated by Django 4.1.7 on 2023-03-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='descriptions',
            field=models.TextField(blank=True, max_length=700, null=True),
        ),
    ]
