# Generated by Django 4.1.7 on 2023-03-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_setting_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='weblink',
            field=models.URLField(default=' ', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
