# Generated by Django 4.1.7 on 2023-03-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardIMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img_ima', models.ImageField(upload_to='ima_service/card/')),
                ('title_slogan_ima', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBenefitIMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_benefit_img_ima', models.ImageField(upload_to='ima_service/customerBenefit/')),
                ('title_ima', models.CharField(max_length=200)),
                ('description_ima', models.TextField(max_length=1024)),
                ('customer_service_ima_1', models.CharField(max_length=200)),
                ('customer_service_ima_2', models.CharField(max_length=200)),
                ('customer_service_ima_3', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceIMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_img_ima', models.ImageField(upload_to='ima_service/service/')),
                ('title_ima', models.CharField(max_length=200)),
                ('description_first_para_ima', models.TextField(max_length=1024)),
                ('description_second_para_ima', models.TextField(max_length=1024)),
                ('service_details_card_title_ima_1', models.CharField(max_length=200)),
                ('service_details_card_details_ima_1', models.CharField(max_length=200)),
                ('service_details_card_title_ima_2', models.CharField(max_length=200)),
                ('service_details_card_details_ima_2', models.CharField(max_length=200)),
            ],
        ),
    ]
