# Generated by Django 4.1.7 on 2023-03-16 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counter',
            old_name='subject',
            new_name='subject_1',
        ),
        migrations.RenameField(
            model_name='counter',
            old_name='value',
            new_name='value_1',
        ),
    ]
