# Generated by Django 4.1.7 on 2023-03-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_rename_subject_counter_subject_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='subject_2',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter',
            name='subject_3',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter',
            name='subject_4',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter',
            name='value_2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counter',
            name='value_3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counter',
            name='value_4',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
